### ISSUE TITLE
Improved Formatting for Subdomains in Updater

### ISSUE THREAD

**Issue by eliasstepanik** [eliasstepanik/IonosDynamicDNSUpdater#1]
I propose a change in the way subdomains are formatted in the updater configuration to make it more organized and easier to understand. Instead of listing all subdomains consecutively under each main domain, I suggest grouping them under their respective main domains as shown below:

Current formatting:
```
environment:
  DOMAIN-0: ""
  DOMAIN-1: ""
  DOMAIN-2: ""
  DOMAIN-3: ""
  DOMAIN-4: ""
  DOMAIN-5: ""
  DOMAIN-6: ""
  DOMAIN-7: ""
  DOMAIN-8: ""
```

Proposed formatting:

```
environment:
  DOMAIN-0: ""
  SUB-0: ""
  SUB-1: ""
  SUB-2: ""
  SUB-3: ""
  SUB-4: ""
  DOMAIN-1: ""
  SUB-0: ""
  SUB-1: ""
  SUB-2: ""
  SUB-3: ""
```

Or even better, with the subdomains indented, if possible:
```
 environment:
      DOMAIN-0: ""
        SUB-0: ""
        SUB-1: ""
        SUB-2: ""
        SUB-3: ""
        SUB-4: ""
      DOMAIN-1: ""
        SUB-0: ""
        SUB-1: ""
        SUB-2: ""
        SUB-3: ""
```

This new formatting will make it easier to manage and visually organize the domains and subdomains in the configuration file.
